### ISSUE TITLE
is this project dead now?

### ISSUE THREAD

**Issue by roeniss** [boj-vs-code/client#21]
좋은 것 같은데 활동이 멈춰서 궁금하여 여쭤봅니다

**Comment by moreal** [comment]
안녕하세요 @roeniss 님.
아직 버려진 프로젝트까지는 아닙니다.

테스트 기능을 추가하면서 구조를 고민하는 과정에서 막혀있었고
사용자가 얼마 없다는 가정하에 임시로 멈춰져 있는 상태였습니다 😅.

**Comment by roeniss** [comment]
답변 감사합니다. 얼마전에 페이스북 그룹 생활코딩에서 vscode ~ leetcode 연동 플러그인을 보고 혹시나 싶어 찾아봤는데 백준도 있어서 반가웠습니다 :) 혹시라도 나중에 본격적으로(?) 리팩토링에 들어가면 같이 개선해나가보고 싶네요! 화이팅입니다. 그리고 좋은 플러그인 감사합니다.
